create table cat_user
(
    id       varchar(64) not null UNIQUE, -- идентификатор текстовый, соответствует логину
    username varchar(255) default 'noname cat',
    nickname varchar(255)
);

create unique index user_id_uindex on cat_user (id);

create table cat_post
(
    id            int generated by default as identity primary key, -- идентификатор целочисленный, автоинкрементный
    author_id     varchar(64) not null,
    description   varchar(500),
    photo_url     varchar(1000),
    creation_date timestamp,
    CONSTRAINT fk_post_author FOREIGN KEY (author_id) REFERENCES cat_user (id)
);

create table cat_follow
(
    id        int generated by default as identity primary key,
    author_id varchar(64) references cat_user (id),
    follow_id varchar(64) references cat_user (id)
);